apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  selector:
    app: comments-service
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-service
spec:
  selector:
    matchLabels:
      app: comments-service
  replicas: 1
  template:
    metadata:
      labels:
        app: comments-service
    spec:
      containers:
        - name: server
          image: tdidok/comments-service
          ports:
            - name: http
              containerPort: 8083